fix: fixed the pipeline yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,18 +19,15 @@ stages:
       fi
 
 .build_template: &build_template
-  <<: *before_script_template
-  image: docker:24.0.5
+  image: docker:latest
   services:
-    - name: docker:24.0.5-dind
-      command: ["--tls=false"]
+    - docker:dind
   variables:
-    DOCKER_TLS_CERTDIR: ""
     DOCKER_HOST: tcp://docker:2375
+    DOCKER_TLS_CERTDIR: ""
     DOCKER_DRIVER: overlay2
   stage: build
   before_script:
-    - apk add --no-cache aws-cli
     - |
       if [[ "$ACCOUNT_OWNER" == "revyrie" ]]; then
         export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_REVYRIE
@@ -43,6 +40,19 @@ stages:
         export AWS_DEFAULT_REGION=$REGION_CLIENT
         export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID_CLIENT
       fi
+    - apk add --no-cache aws-cli
+    - |
+      echo "Waiting for Docker daemon..."
+      retries=0
+      while ! docker info &>/dev/null; do
+        if [ $retries -ge 30 ]; then
+          echo "Docker daemon failed to start."
+          exit 1
+        fi
+        retries=$((retries+1))
+        sleep 1
+      done
+      echo "Docker daemon is ready."
   script:
     - echo "🔐 Logging in to ECR"
     - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
